//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MyWebShopContract", ConfigurationName="ServiceReference1.IWebshop")]
    public interface IWebshop {
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetData", ReplyAction="MyWebShopContract/IWebshop/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetData", ReplyAction="MyWebShopContract/IWebshop/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetDataUsingDataContract", ReplyAction="MyWebShopContract/IWebshop/GetDataUsingDataContractResponse")]
        MyWebshopContract.CompositeType GetDataUsingDataContract(MyWebshopContract.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetDataUsingDataContract", ReplyAction="MyWebShopContract/IWebshop/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MyWebshopContract.CompositeType> GetDataUsingDataContractAsync(MyWebshopContract.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetWebshopName", ReplyAction="MyWebShopContract/IWebshop/GetWebshopNameResponse")]
        string GetWebshopName();
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetWebshopName", ReplyAction="MyWebShopContract/IWebshop/GetWebshopNameResponse")]
        System.Threading.Tasks.Task<string> GetWebshopNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetProductList", ReplyAction="MyWebShopContract/IWebshop/GetProductListResponse")]
        string GetProductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetProductList", ReplyAction="MyWebShopContract/IWebshop/GetProductListResponse")]
        System.Threading.Tasks.Task<string> GetProductListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetProductInfo", ReplyAction="MyWebShopContract/IWebshop/GetProductInfoResponse")]
        string GetProductInfo(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/GetProductInfo", ReplyAction="MyWebShopContract/IWebshop/GetProductInfoResponse")]
        System.Threading.Tasks.Task<string> GetProductInfoAsync(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/BuyProduct", ReplyAction="MyWebShopContract/IWebshop/BuyProductResponse")]
        bool BuyProduct(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="MyWebShopContract/IWebshop/BuyProduct", ReplyAction="MyWebShopContract/IWebshop/BuyProductResponse")]
        System.Threading.Tasks.Task<bool> BuyProductAsync(string ProductId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebshopChannel : WebShopClient.ServiceReference1.IWebshop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebshopClient : System.ServiceModel.ClientBase<WebShopClient.ServiceReference1.IWebshop>, WebShopClient.ServiceReference1.IWebshop {
        
        public WebshopClient() {
        }
        
        public WebshopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebshopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebshopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebshopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MyWebshopContract.CompositeType GetDataUsingDataContract(MyWebshopContract.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MyWebshopContract.CompositeType> GetDataUsingDataContractAsync(MyWebshopContract.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetWebshopName() {
            return base.Channel.GetWebshopName();
        }
        
        public System.Threading.Tasks.Task<string> GetWebshopNameAsync() {
            return base.Channel.GetWebshopNameAsync();
        }
        
        public string GetProductList() {
            return base.Channel.GetProductList();
        }
        
        public System.Threading.Tasks.Task<string> GetProductListAsync() {
            return base.Channel.GetProductListAsync();
        }
        
        public string GetProductInfo(string ProductId) {
            return base.Channel.GetProductInfo(ProductId);
        }
        
        public System.Threading.Tasks.Task<string> GetProductInfoAsync(string ProductId) {
            return base.Channel.GetProductInfoAsync(ProductId);
        }
        
        public bool BuyProduct(string ProductId) {
            return base.Channel.BuyProduct(ProductId);
        }
        
        public System.Threading.Tasks.Task<bool> BuyProductAsync(string ProductId) {
            return base.Channel.BuyProductAsync(ProductId);
        }
    }
}
